version: '3'
services:
  cloudapi:
    build: .
    ports:
      - "50052:50052"
  devmandbackend:
    image: frinx/dvmnd-test
    depends_on:
      - cloudapi
    command: bash -c "mkdir -p /run/sshd && /usr/sbin/sshd && cp -r -n ../build_copy/* ../build && cd ../build && sed -i 's/127.0.0.1:50052/cloudapi:50052/g' config-sample/dev_conf.yaml && bash -c '(sleep 4 && ./devmand --logtostderr=1 --device_configuration_file=config-sample/dev_conf.yaml & cd js_plugins && nodemon plugin-linux-ifc-reader.js)'"
    volumes:
      - ${HOME}/cache_devmand_build:/cache/devmand/build
networks:
  default:
    external:
      name: frinx-machine_default
